spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: resume
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/resume/**
        - id: notification
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/notification/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG