spring:
  application:
    name: notification
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10   # heartbeat every 10s
    lease-expiration-duration-in-seconds: 30

server:
  port: 8082